const citas = [
  {"cita":"Frankly, my dear, I don't give a damn",
    "autor": "Clark Gable",
  "img":"/clark_gable.jpg"},
  {"cita":"I'm gonna make him an offer he can't refuse",
  "autor": "Marlon Brando",
  "img":"/marlon_brando.jpg"},
  {"cita":"Toto, I've a feeling we're not in Kansas anymore",
    "autor":"Judy Garland",
    "img":"/judy_garland.jpg"},
  {"cita":"We always have Paris",
    "autor": "Humprey Bogart",
    "img":"/humprey_bogart.jpg"},
  {"cita": "May the Force be with you",
    "autor":"Harrison Ford",
    "img":"/harrison_ford.jpg"},
  {"cita":"You talking to me?",
    "autor": "Robert De Niro",
    "img":"/robert_de_niro.jpg"},
  {"cita":"I love the smell of napalm in the morning",
    "autor":"Robert Duvall",
    "img":"/robert_duvall.jpg"},
  {"cita":"E.T. phone home",
    "autor":"E.T",
    "img":"/et.jpg"},
  {"cita":"Show me the money!",
    "autor":"Tom Cruise",
    "img":"/tom_cruise.jpg"},
  {"cita": "You're gonna need a bigger boat",
    "autor":"Robert Shaw",
    "img":"/robert_shaw.jpg"},
  {"cita":"I'll be back",
    "autor": "Arnold Schwarzenegger",
    "img":"/arnold.jpg"},
  {"cita": "I see dead people",
    "autor":"Haley Joel Osment",
    "img":"/haley_joel.jpg"},
  {"cita":"Houston, we have a problem",
    "autor":"Tom Hanks",
    "img":"/tom_hanks.jpg"},
  {"cita":"You had me at 'Hello'",
    "autor":"Renée Zellweger",
    "img":"/renee_zellweger.jpeg"},
  {"cita":"Here's Johnny!" ,
    "autor":"Jack Nicholson",
    "img":"/jack_nicholson.jpg"},
  {"cita":"No wire hangers, ever!",
    "autor":"Faye Dunaway",
    "img":"/faye_dunaway.jpg"}
  

]

export default citas;